backend:
  name: github
  repo: meadowlarque/uvapjson
  branch: main

media_folder: static/assets
public_folder: /assets

collections:
  - name: 'news'
    label: 'News'
    folder: 'content/news'
    publish_mode: editorial_workflow
    preview_path: '{{title}}/index'
    create: true
    slug: 'index'
    media_folder: ''
    public_folder: ''
    path: '{{title}}/index'
    fields:
      - { name: path, label: Path, required: false, }
      - { label: "Type", name: "type",widget: "select", options: ["news", "event", "media", "page", 'promo'], required: true}
      - { label: "Is Draft?", name: "draft", widget: "string", default: "false"}
      - { name: title, label: Title }
      - { label: 'related book id', name: 'relbook', widget: 'list', required: false }
      - { name: body, label: Body, widget: markdown }
      - { label: 'Description', name: 'description', widget: 'string', required: false }
      - { label: 'YouTube Link', name: 'link', widget: 'string', required: false }

    
 

  - name: 'pages'
    identifier_field: '{{title}}'
    label: 'Pages'
    folder: 'content/pages'
    preview_path: '{{title}}/index'
    create: true
    slug: 'index'
    media_folder: ''
    public_folder: ''
    path: '{{title}}/index'
    fields:
      - { name: path, label: Path, required: false, }
      - { label: 'Type', name: 'type', widget: 'select', options: ['news', 'event', 'media', 'page', 'promo'], required: true}  
      - { name: title, label: Title }
      - { name: body, label: Body, widget: markdown }

  - name: 'promo'
    label: 'Promotion'
    identifier_field: '{{title}}'
    folder: 'content/promos'
    preview_path: '{{title}}/index'
    create: true
    slug: 'index'
    media_folder: ''
    public_folder: ''
    path: '{{title}}/index'      
    fields:
      - { label: 'Type', name: 'type', widget: 'select', options: ['news', 'event', 'media', 'page', 'promo'], required: true}  
      - { name: title, label: Title }
      - { label: 'related book id', name: 'relbook', widget: 'list', required: false }
      - { name: body, label: Body, widget: markdown }
      - { label: 'Description', name: 'description', widget: 'string', required: false }

