backend:
  name: github
  repo: meadowlarque/uvapjson
  branch: main

media_folder: static/assets
public_folder: /assets

collections:
  - name: 'news'
    label: 'News'
    folder: 'content/news'
    publish_mode: editorial_workflow
    preview_path: '{{title}}/index'
    create: true
    slug: 'index'
    media_folder: ''
    public_folder: ''
    path: '{{title}}/index'
    fields:
      - { label: 'Type', name: 'type', widget: 'select', options: ['news', 'event', 'media'], required: true}  
      - { label: "Is Draft?", name: "draft", widget: "string", default: "false"}
      - { name: title, label: Title }
      - { label: 'related book id', name: 'relbook', widget: 'list', required: false }
      - { label: 'Summary', name: 'description', widget: 'string', required: false, hint: 'Text for homepage and previews'}
      - { name: body, label: Body, widget: markdown }
      
  - name: 'pages'
    identifier_field: '{{title}}'
    label: 'Pages'
    folder: 'content/pages'
    preview_path: '{{title}}/index'
    create: true
    slug: 'index'
    media_folder: ''
    public_folder: ''
    path: '{{title}}/index'
    fields:
      - { name: path, label: Path, required: false, }
      - { label: 'Type', name: 'type', widget: 'select', options: ['news', 'event', 'media', 'page', 'promo', 'series'], required: true, default: ['pages']}  
      - { name: title, label: Title }
      - { name: body, label: Body, widget: markdown }
      - { label: 'Internal Tag', name: 'int_tag', widget: 'select', options: ['authors'], required: false}  


  - name: 'promo'
    label: 'Promotion'
    identifier_field: '{{title}}'
    folder: 'content/promos'
    preview_path: '{{title}}/index'
    create: true
    slug: 'index'
    media_folder: ''
    public_folder: ''
    path: '{{title}}/index'      
    fields:
      - { label: 'Type', name: 'type', widget: 'select', options: ['news', 'event', 'media', 'page', 'promo', 'series'], required: true, default: ['promo']}  
      - { name: title, label: Title }
      - { label: 'related book id', name: 'relbook', widget: 'list', required: false }
      - { name: body, label: Body, widget: markdown }
      - { label: 'Summary', name: 'description', widget: 'string', required: false, hint: 'Text for homepage and previews'}

  - name: 'series_info'
    identifier_field: '{{title}}'
    label: 'Series Info'
    folder: 'content/seriesinfo'
    preview_path: '{{title}}/index'
    create: true
    slug: 'index'
    media_folder: ''
    public_folder: ''
    path: '{{title}}/index'
    fields:
      - { label: 'Type', name: 'type', widget: 'select', options: ['news', 'event', 'media', 'page', 'promo', 'series'], required: true, default: ['series']}  
      - { name: title, label: Title }
      - { label: 'Series Status', name: 'status', widget: 'select', options: ['active', 'completed'], required: true} 
      - { label: 'Series Type', name: 'seriestype', widget: 'select', options: ['Academic Book Series', 'Documentary Editions','Lecture Series', 'Distributed Series'], required: true}  
      - { label: 'Series Editors', name: 'editors', widget: 'string', required: false }
      - { label: 'UVaP Editor', name: 'uvaeditors', widget: 'string', required: false }
      - { name: body, label: Body, widget: markdown }
      - { label: 'Series Slug', name: 'slug', widget: 'string', required: false, hint:'In case need to match URL-friendly Series name' }

           
